import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5', // 浅灰色背景，营造简洁感
  },
  headerText: {
    fontFamily: 'Playfair Display, serif', // 使用更文艺的字体
    fontSize: 28,
    marginBottom: 20,
    color: '#2C3E50', // 深蓝灰色，增加成熟感
    letterSpacing: 1, // 增加字母间距
  },
  podcastItem: {
    height: 220,
    marginBottom: 25,
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  podcastImage: {
    width: '100%',
    height: '100%',
  },
  podcastGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '60%',
    justifyContent: 'flex-end',
    padding: 20,
  },
  podcastTitle: {
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  podcastAuthor: {
    fontFamily: 'Lato, sans-serif',
    fontSize: 16,
    color: '#E0E0E0',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  playerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 30,
    backgroundColor: '#2C3E50', // 深蓝灰色背景
  },
  backButton: {
    position: 'absolute',
    top: 40,
    left: 20,
    zIndex: 10,
    padding: 10,
    backgroundColor: '#007AFF',
    borderRadius: 20,
  },
  playerImage: {
    width: 280,
    height: 280,
    borderRadius: 140,
    marginTop: 60,
    marginBottom: 40,
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  playerTitle: {
    fontFamily: 'Playfair Display, serif',
    fontSize: 26,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 12,
    textAlign: 'center',
    maxWidth: '80%',
  },
  playerAuthor: {
    fontFamily: 'Lato, sans-serif',
    fontSize: 18,
    color: '#B2BABB',
    marginBottom: 35,
  },
  slider: {
    width: '100%',
    height: 40,
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  timeText: {
    fontFamily: 'Lato, sans-serif',
    fontSize: 14,
    color: '#B2BABB',
  },
  controlsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
  },
  controlButton: {
    padding: 15,
  },
  playButton: {
    backgroundColor: '#3498DB',
    padding: 25,
    borderRadius: 50,
    marginHorizontal: 30,
  },
  aiButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: 12,
    borderRadius: 25,
    marginTop: 30,
  },
  aiButtonText: {
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 16,
    color: '#fff',
    marginLeft: 8,
  },
  aiContainer: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
  },
  aiHeaderText: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 28,
    color: '#fff',
    marginBottom: 30,
    marginTop: 40,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 20,
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    color: '#fff',
    fontFamily: 'Montserrat_400Regular',
    marginBottom: 10,
  },
  generateButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  generatingButton: {
    backgroundColor: '#45a049',
  },
  buttonText: {
    fontFamily: 'Montserrat_600SemiBold',
    color: 'white',
    fontSize: 16,
  },
  generatedPodcast: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 20,
    borderRadius: 10,
    marginTop: 20,
    width: '100%',
  },
  generatedTitle: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 20,
    color: '#fff',
    marginBottom: 10,
  },
  generatedContent: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 16,
    color: '#ddd',
  },
  lyricContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  lyricText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
  },
  errorText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 18,
    color: 'red',
    textAlign: 'center',
    marginTop: 20,
  },
  channelRow: {
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  channelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  channelImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 15,
  },
  channelTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  channelHeaderImage: {
    width: '100%',
    height: 250,
  },
  channelHeaderGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 250,
    justifyContent: 'space-between',
    padding: 20,
  },
  channelHeaderTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  channelContent: {
    padding: 20,
  },
  episodesHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  episodeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  episodeImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
  },
  episodeInfo: {
    flex: 1,
  },
  episodeTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  episodeAuthor: {
    fontSize: 14,
    color: '#999',
  },
  episodeDate: {
    fontSize: 12,
    color: '#999',
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    color: '#fff',
    fontFamily: 'Montserrat_400Regular',
    marginBottom: 10,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 20,
  },
  logoutButton: {
    margin: 20,
    backgroundColor: '#ff3b30',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  logoutText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  header: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 10,
  },
  email: {
    fontSize: 16,
    color: '#888',
    marginTop: 5,
  },
  section: {
    marginTop: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    marginHorizontal: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  option: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  adOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 10,
    alignItems: 'center',
  },
  adText: {
    color: 'white',
    fontSize: 16,
  },
});
